# sudo docker exec -it f7d48f8654da /bin/bash - нужен id контейнера
# psql -U gym -d gym
version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    ports:
      - "5432:5432"
    # volumes: 
      # - ./db/migrations/:/docker-entrypoint-initdb.d
      # - ../.:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym -d gym"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  golang:
    build:
      context: .
      dockerfile: api.Dockerfile 
    ports:
      - "8080:8080"
    environment:
      - HOST=${HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - net

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    # environment:
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_PORT=${REDIS_PORT}
      # - REDIS_DATABASES=${REDIS_DATABASES}
    networks:
      - net

networks:
  net: